"""init database migration

Revision ID: 4bfb66ea3e44
Revises: 
Create Date: 2026-06-22 18:59:58.061818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfb66ea3e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User cần xác thực email'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Mã xác thực email'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Thời gian hết hạn mã'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='Mã đã được sử dụng hay chưa'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Thời gian tạo mã'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_verification')
    # ### end Alembic commands ###
