"""change gender to enum

Revision ID: ae6507147a87
Revises: d99b0ca68a7e
Create Date: 2026-07-03 00:07:47.914948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae6507147a87'
down_revision = 'd99b0ca68a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20),
               type_=sa.Enum('MALE', 'FEMALE', 'DEFAULT', name='genderrole'),
               existing_comment='Giới tính',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'DEFAULT', name='genderrole'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=20),
               existing_comment='Giới tính',
               existing_nullable=True)

    # ### end Alembic commands ###
